/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.gui2;

import Excepciones.BaseException;
import fachada.Quimico;
import fachada.Residuo;
import fachada.Solicitud;
import java.util.List;
import javax.swing.JOptionPane;
import logica.logica2.FabricaLogica;
import logica.logica2.ILogica;

/**
 *
 * @author Alan Rodriguez
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        btnRegistrarResiduo = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        botonAsignarTraslado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarResiduo.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarResiduo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRegistrarResiduo.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarResiduo.setText("Registrar residuo");
        btnRegistrarResiduo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 162, 255), 3, true));
        btnRegistrarResiduo.setFocusPainted(false);
        btnRegistrarResiduo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRegistro(evt);
            }
        });
        background.add(btnRegistrarResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 110));

        btn.setBackground(new java.awt.Color(255, 255, 255));
        btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn.setForeground(new java.awt.Color(0, 0, 0));
        btn.setText("Solicitar traslado");
        btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 162, 255), 3, true));
        btn.setFocusPainted(false);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSolicitarTraslado(evt);
            }
        });
        background.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 110));

        botonAsignarTraslado.setBackground(new java.awt.Color(255, 255, 255));
        botonAsignarTraslado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonAsignarTraslado.setForeground(new java.awt.Color(0, 0, 0));
        botonAsignarTraslado.setText("Asignar Traslado");
        botonAsignarTraslado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 162, 255), 3, true));
        botonAsignarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAsignar(evt);
            }
        });
        background.add(botonAsignarTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectRegistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRegistro
        ILogica logica = FabricaLogica.crearInstancia();
        try {
            List<Quimico> listaQuimicos = logica.obtenerTodosLosQuimicos();
            new FrmRegistroResiduo(listaQuimicos, logica).setVisible(true);
        } catch (BaseException e) {
            muestraMensajeError(e.getMessage());
        }

    }//GEN-LAST:event_selectRegistro

    private void selectSolicitarTraslado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSolicitarTraslado

        ILogica logica = FabricaLogica.crearInstancia();
        try {
            List<Residuo> listaResiduos = logica.obtenerTodosLosResiduosDeProductor("ITSON");
            new FrmSolicitarTraslado(listaResiduos);
        } catch (BaseException e) {
            muestraMensajeError(e.getMessage());
        }

    }//GEN-LAST:event_selectSolicitarTraslado

    private void selectAsignar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAsignar
        ILogica logica = FabricaLogica.crearInstancia();

        try {
            List<Solicitud> solicitudes = logica.obtenerTodasLasSolicitudes();
            new FrmSolicitudes(solicitudes).setVisible(true);
        } catch (BaseException e) {
            muestraMensajeError(e.getMessage());
        }
    }//GEN-LAST:event_selectAsignar

    private void muestraMensajeError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonAsignarTraslado;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnRegistrarResiduo;
    // End of variables declaration//GEN-END:variables
}
