/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Quimico;
import java.util.List;
import pkg.FabricaLogica;
import pkg.ILogica;

/**
 *
 * @author Alan Rodriguez
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarResiduo = new javax.swing.JButton();
        btnSolicitarTraslado = new javax.swing.JButton();
        btnRegistrarTraslado = new javax.swing.JButton();
        btnAsignarTraslado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Residuos");
        panelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        background.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 60));

        btnRegistrarResiduo.setText("Registrar residuo");
        btnRegistrarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarResiduoActionPerformed(evt);
            }
        });
        background.add(btnRegistrarResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 70));

        btnSolicitarTraslado.setText("Solicitar traslado");
        background.add(btnSolicitarTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 80));

        btnRegistrarTraslado.setText("Registrar Traslado");
        background.add(btnRegistrarTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, 80));

        btnAsignarTraslado.setText("Asignar traslado");
        background.add(btnAsignarTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, 70));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarResiduoActionPerformed
        ILogica logica = FabricaLogica.crearInstancia();
        
        List<Quimico> listaQuimicos = logica.obtenerTodosLosQuimicos();
        
        new FrmRegistroResiduo(listaQuimicos, logica).setVisible(true);
        
        
        
    }//GEN-LAST:event_btnRegistrarResiduoActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAsignarTraslado;
    private javax.swing.JButton btnRegistrarResiduo;
    private javax.swing.JButton btnRegistrarTraslado;
    private javax.swing.JButton btnSolicitarTraslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
