/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Quimico;
import Entidades.Residuo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pkg.ILogica;

/**
 *
 * @author Rosa Rodriguez
 */
public class FrmRegistroResiduo extends javax.swing.JFrame {

    private ILogica logica;
    
    /**
     * Creates new form FrmRegistroTraslados
     */
    public FrmRegistroResiduo(List<Quimico> lista, ILogica logica) {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)tablaTodos.getModel();
        for(Quimico q : lista) {
            Object[] row = {0, q.getNombre()};
            model.addRow(row);
        }
        this.logica = logica;
    }

    private void mueveQuimicoALaLista() {
        int row = tablaTodos.getSelectedRow();
        
        if(row < 0 ) {
            return;
        }
        
        String n = (String)tablaTodos.getValueAt(row, 1);
        Quimico q = new Quimico();
        q.setNombre(n);
        
        DefaultTableModel dtm = (DefaultTableModel)tablaSelect.getModel();
        dtm.addRow(new Object[]{0, q.getNombre()});
        DefaultTableModel m = (DefaultTableModel)tablaTodos.getModel();
        m.removeRow(row);
    }
    
    private void regresaQuimicoALaLista() {
        int row = tablaSelect.getSelectedRow();
        
        if(row < 0 ) {
            return;
        }
        
        String n = (String)tablaSelect.getValueAt(row, 1);
        Quimico q = new Quimico();
        q.setNombre(n);
        
        DefaultTableModel dtm = (DefaultTableModel)tablaTodos.getModel();
        dtm.addRow(new Object[]{0, q.getNombre()});
        DefaultTableModel m = (DefaultTableModel)tablaSelect.getModel();
        m.removeRow(row);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSelect = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTodos = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "quimicos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSelect);
        if (tablaSelect.getColumnModel().getColumnCount() > 0) {
            tablaSelect.getColumnModel().getColumn(0).setResizable(false);
            tablaSelect.getColumnModel().getColumn(1).setResizable(false);
        }

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        tablaTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "quimico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTodos);
        if (tablaTodos.getColumnModel().getColumnCount() > 0) {
            tablaTodos.getColumnModel().getColumn(0).setResizable(false);
            tablaTodos.getColumnModel().getColumn(1).setResizable(false);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 170, 160));

        agregar.setText("<");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        background.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        regresar.setText(">");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        background.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btnGuardar.setText("Guardar residuo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        background.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        btnSalir.setText("Salir");
        background.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, -1));

        jLabel1.setText("Nombre");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        background.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        mueveQuimicoALaLista();
    }//GEN-LAST:event_agregarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        regresaQuimicoALaLista();
    }//GEN-LAST:event_regresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        Residuo r = new Residuo();
        List<Quimico> quimicos = new ArrayList();
        DefaultTableModel m = (DefaultTableModel)tablaSelect.getModel();
        int rows = m.getRowCount();
        
        for(int i = 0; i<rows; i++) {
            quimicos.add(new Quimico((String)m.getValueAt(i, 1)));
        }
        
        r.setQuimicos(quimicos);
        r.setCodigo(txtNombre.getText());
        try {
            r.verificar();
        } catch (Exception e) {
            mostrarError(e.getMessage());
            return;
        }
        
        boolean existeOtro = logica.comprobarResiduo(r);
        
        if(existeOtro) {
            mostrarError("EL RESIDUO QUE INTENTA INGRESAR YA EXISTE");
            return;
        }
        
        logica.guardarResiduo(r);
        muestraMensajeConfirmacion("SI SE PUDO INGRESAR");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void muestraMensajeConfirmacion(String msg) {
        JOptionPane.showMessageDialog(this, msg, "YUPII", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tablaSelect;
    private javax.swing.JTable tablaTodos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
